### ISSUE TITLE
Create a menu

### ISSUE THREAD

**Issue by eyu776** [eyu776/python-exercise#1]
### User Story
As a user, I would like to be able to select options from a menu when using the program, so the program is easier for me to use.

### Task List
- [x] Implement option for quitting
- [x] Implement option for listing all movies
- [x] Implement option for searching by movie
- [x] Implement option for searching by cast
- [x] Handle invalid input from user

### Acceptance Criteria
* the menu should have an option for q for quit, when the user types q, the program exits
* if the user types any invalid option, the menu will re-appear for the user to type again
* the menu should not be case-sensitive
