### ISSUE TITLE
List all the movie names

### ISSUE THREAD

**Issue by eyu776** [eyu776/python-exercise#2]
### User Story
As a user, I would like to be able to view all movie names from the program, because I cannot remember all of the movies in the list. So it would be convenient to have an option to list them all.

### Task List
- [x] Implement code to retrieve all movies from program
- [x] Implement code to print out all movies to the screen
- [x] Connect code to menu so user can access the new functionality

### Acceptance Criteria
* user should see all movie names printed to the screen
* user should see each movie printed on a new line

**Comment by eyu776** [comment]
Ignore "Search movies by names" I linked the wrong issue on my PR on accident (fixed now).
