### ISSUE TITLE
Search movies by cast

### ISSUE THREAD

**Issue by eyu776** [eyu776/python-exercise#4]
### User Story
As a user, I want to be able to search for movies by the cast. The list of movies is too long for me to efficiently search through the cast members myself, so it would be convenient to have search functionality.

### Task List
- [x] Implement code to retrieve the search phrase from the user
- [x] Implement code to search through the movies list without case sensitivity
- [x] Implement code to return all matches from the search
- [x] Connect code to menu so user can access new functionality

### Acceptance Criteria
* code should be able to search for matches in a case-insensitive fashion
* code should display movies of all possible matches by the search phrase from the user in the cast member information for each movie
* code should not repeat movies which have cast members that fulfill the search phrase multiple times
